import strategies

presets = {
    'test': {
        'name': '攻伤暴/攻双暴',
        'mains_description': '攻伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'atkp',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '攻双暴1',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 1,
            'defp': 0,
            'em': 0,
            'er': 0,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '全部强化',
        'strategy': {
            'flower': strategies.s_all,
            'plume': strategies.s_all,
            'sands': strategies.s_all,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精/充',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'dps': {
        'name': '攻伤暴/攻双暴',
        'mains_description': '攻伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'atkp',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻0.5/充精0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.25,
            'er': 0.25,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精/充',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'dps_em': {
        'name': '攻伤暴/攻精双暴',
        'mains_description': '攻伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'atkp',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻精0.5/充0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.5,
            'er': 0.25,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻精双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精通',
                'weight': 1,
                'linecolor': 'blue',
            },
            'er': {
                'name': '充能',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'dps_emer': {
        'name': '攻伤暴/攻精充双暴',
        'mains_description': '攻伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'atkp',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻精充0.5',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.5,
            'er': 0.5,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻精充双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精/充',
                'weight': 2,
                'linecolor': 'blue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'emdps': {
        'name': '精伤暴/攻双暴',
        'mains_description': '精伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'em',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻0.5/充精0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.25,
            'er': 0.25,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精通',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'er': {
                'name': '充能',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'emdps_em': {
        'name': '精伤暴/攻精双暴',
        'mains_description': '精伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'em',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻精0.5/充0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.5,
            'er': 0.25,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻精双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精通',
                'weight': 1,
                'linecolor': 'blue',
            },
            'er': {
                'name': '充能',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'emdps_emer': {
        'name': '精伤暴/攻精充双暴',
        'mains_description': '精伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'em',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻精充0.5',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.5,
            'er': 0.5,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻精充双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精通',
                'weight': 1,
                'linecolor': 'blue',
            },
            'er': {
                'name': '充能',
                'weight': 1,
                'linecolor': 'blue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'erdps': {
        'name': '充伤暴/攻双暴',
        'mains_description': '充伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'er',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻0.5/充精0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.25,
            'er': 0.25,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精通',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'er': {
                'name': '充能',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'erdps_em': {
        'name': '充伤暴/攻精双暴',
        'mains_description': '充伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'er',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻精0.5/充0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.5,
            'er': 0.25,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻精双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精通',
                'weight': 1,
                'linecolor': 'blue',
            },
            'er': {
                'name': '充能',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'erdps_emer': {
        'name': '充伤暴/攻精充双暴',
        'mains_description': '充伤暴',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'er',
            'goblet': 'pyroDB',
            'circlet': 'cr',
        },
        'weight_description': '双暴1/攻精充0.5',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.5,
            'defp': 0,
            'em': 0.5,
            'er': 0.5,
            'cr': 1,
            'cd': 1,
        },
        'strategy_description': '花/羽只强化初始含双暴或1暴2攻精充的\n沙只强化初始含双暴或1暴1攻精充的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_1c2a,
            'plume': strategies.s_1c2a,
            'sands': strategies.s_1c1a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '攻精充双暴',
        'format': {
            'cr': {
                'name': '暴击',
                'weight': 1,
                'linecolor': 'red',
            },
            'cd': {
                'name': '爆伤',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'blue',
            },
            'em': {
                'name': '精通',
                'weight': 1,
                'linecolor': 'blue',
            },
            'er': {
                'name': '充能',
                'weight': 1,
                'linecolor': 'blue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'emsup': {
        'name': '精精精/精充',
        'mains_description': '精精精',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'em',
            'goblet': 'em',
            'circlet': 'em',
        },
        'weight_description': '精充1/攻双暴0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0.25,
            'defp': 0,
            'em': 1,
            'er': 1,
            'cr': 0.25,
            'cd': 0.25,
        },
        'strategy_description': '花/羽只强化初始含精充的\n沙只强化初始含充能的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_2e,
            'plume': strategies.s_2e,
            'sands': strategies.s_er,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '精充',
        'format': {
            'em': {
                'name': '精通',
                'weight': 1,
                'linecolor': 'red',
            },
            'er': {
                'name': '充能',
                'weight': 1,
                'linecolor': 'red',
            },
            'cr': {
                'name': '暴/爆',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atkp': {
                'name': '大攻击',
                'weight': 0,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'healsup_em': {
        'name': '精攻治/攻精充',
        'mains_description': '精攻治',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'em',
            'goblet': 'atkp',
            'circlet': 'hb',
        },
        'weight_description': '攻精充1/双暴0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 1,
            'defp': 0,
            'em': 1,
            'er': 1,
            'cr': 0.25,
            'cd': 0.25,
        },
        'strategy_description': '花/羽只强化初始含3攻精充的\n沙只强化初始含1攻充的\n杯只强化初始含精充的\n头均强化',
        'strategy': {
            'flower': strategies.s_3a,
            'plume': strategies.s_3a,
            'sands': strategies.s_1a,
            'goblet': strategies.s_2e,
            'circlet': strategies.s_all,
        },
        'format_name': '攻精充',
        'format': {
            'atkp': {
                'name': '大攻击',
                'weight': 0,
                'linecolor': 'red',
            },
            'em': {
                'name': '精通',
                'weight': 1,
                'linecolor': 'red',
            },
            'er': {
                'name': '充能',
                'weight': 1,
                'linecolor': 'red',
            },
            'cr': {
                'name': '暴/爆',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'healsup_dbhp': {
        'name': '生伤治/生充',
        'mains_description': '生伤治',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'hpp',
            'goblet': 'hydroDB',
            'circlet': 'hb',
        },
        'weight_description': '生充1/攻精0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 1,
            'atkp': 0.25,
            'defp': 0,
            'em': 0.25,
            'er': 1,
            'cr': 0,
            'cd': 0,
        },
        'strategy_description': '花/羽只强化初始含2生充1攻精的\n沙只强化初始含攻充精的\n杯/头均强化',
        'strategy': {
            'flower': strategies.s_2h1a,
            'plume': strategies.s_2h1a,
            'sands': strategies.s_3a,
            'goblet': strategies.s_all,
            'circlet': strategies.s_all,
        },
        'format_name': '生充',
        'format': {
            'hpp': {
                'name': '大生命',
                'weight': 1,
                'linecolor': 'red',
            },
            'er': {
                'name': '充能',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '攻/精',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'hp': {
                'name': '小生命',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'healsup_hp': {
        'name': '生生治/生充',
        'mains_description': '生生治',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'hpp',
            'goblet': 'hpp',
            'circlet': 'hb',
        },
        'weight_description': '生充1/攻精0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 1,
            'atkp': 0.25,
            'defp': 0,
            'em': 0.25,
            'er': 1,
            'cr': 0,
            'cd': 0,
        },
        'strategy_description': '花/羽只强化初始含2生充1攻精的\n沙/杯只强化初始含攻充精的\n头均强化',
        'strategy': {
            'flower': strategies.s_2h1a,
            'plume': strategies.s_2h1a,
            'sands': strategies.s_3a,
            'goblet': strategies.s_3a,
            'circlet': strategies.s_all,
        },
        'format_name': '生充',
        'format': {
            'hpp': {
                'name': '大生命',
                'weight': 1,
                'linecolor': 'red',
            },
            'er': {
                'name': '充能',
                'weight': 1,
                'linecolor': 'red',
            },
            'atkp': {
                'name': '攻/精',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'hp': {
                'name': '小生命',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'defsup': {
        'name': '防防防/防充',
        'mains_description': '防防防',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'defp',
            'goblet': 'defp',
            'circlet': 'defp',
        },
        'weight_description': '防充1/双暴0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 0,
            'defp': 1,
            'em': 0,
            'er': 1,
            'cr': 0.25,
            'cd': 0.25,
        },
        'strategy_description': '花/羽只强化初始含2防充的\n沙/杯/头只强化初始含1充1暴的',
        'strategy': {
            'flower': strategies.s_2d,
            'plume': strategies.s_2d,
            'sands': strategies.s_1e1c,
            'goblet': strategies.s_1e1c,
            'circlet': strategies.s_1e1c,
        },
        'format_name': '防充',
        'format': {
            'defp': {
                'name': '大防御',
                'weight': 1,
                'linecolor': 'red',
            },
            'er': {
                'name': '充能',
                'weight': 1,
                'linecolor': 'red',
            },
            'cr': {
                'name': '暴/爆',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'def': {
                'name': '小防御',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
    'atksup': {
        'name': '攻攻攻/攻充',
        'mains_description': '攻攻攻',
        'mains': {
            'flower': 'hp',
            'plume': 'atk',
            'sands': 'atkp',
            'goblet': 'atkp',
            'circlet': 'atkp',
        },
        'weight_description': '攻充1/双暴0.25',
        'weight': {
            'hp': 0,
            'atk': 0,
            'def': 0,
            'hpp': 0,
            'atkp': 1,
            'defp': 0,
            'em': 0,
            'er': 1,
            'cr': 0.25,
            'cd': 0.25,
        },
        'strategy_description': '花/羽只强化初始含2攻充的\n沙/杯/头只强化初始含1充1暴的',
        'strategy': {
            'flower': strategies.s_2a,
            'plume': strategies.s_2a,
            'sands': strategies.s_1e1c,
            'goblet': strategies.s_1e1c,
            'circlet': strategies.s_1e1c,
        },
        'format_name': '攻充',
        'format': {
            'atkp': {
                'name': '大攻击',
                'weight': 1,
                'linecolor': 'red',
            },
            'er': {
                'name': '充能',
                'weight': 1,
                'linecolor': 'red',
            },
            'cr': {
                'name': '暴/爆',
                'weight': 0,
                'linecolor': 'lightblue',
            },
            'atk': {
                'name': '小攻击',
                'weight': 0.3,
                'linecolor': 'lightblue',
            },
        },
    },  # EOP
}
